### ISSUE TITLE
[Feature Request]: Tabs component

### ISSUE THREAD

**Issue by somethingxdev** [withstudiocms/ui#7]
### Describe your feature request

Add the tabs component as in the Modular by design section.

### Other examples?

https://ui.studiocms.dev/

**Comment by studiocms-no-reply** [comment]
Hi @somethingxdev 👋
Welcome to the StudioCMS project! We're excited to have you here. Thanks for opening your first issue! 🎉
If you are reporting a bug, please make sure to include the following information in your issue: - A clear description of the issue - Steps to reproduce the issue - Expected behavior - Actual behavior - Environment details (OS, hardware, etc.)
If you have any questions or need help, feel free to ask. We're here to help you! 🚀
If you're interested in contributing to the project, please check out our [Contributing Guide](https://github.com/withstudiocms/.github/blob/main/CONTRIBUTING.md) and join our [Discord community](https://chat.studiocms.dev) to stay in the loop for any future help we may need!
Thanks again for opening your first issue! 🙌
- The StudioCMS Team
